server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jokes?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 'root'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
jokes:
  url: "https://api.chucknorris.io/jokes/random"
  numberOfJokes: 20